/**
 * RAVEN - Seed data & defaults
 * Initial catalog, categories, banners for LocalStorage bootstrap
 */
const RAVEN_SEED = {
  settings: {
    siteName: 'RAVEN',
    currency: '৳',
    shippingFee: 120,
    freeShippingMin: 2500,
    theme: 'light',
    newsletterText: 'Join the RAVEN list for drops, sales & streetwear news.',
  },
  admin: {
    email: 'mdnuhad534@gmail.com',
    password: 'Raven@Admin2026',
  },
  categories: [
    { id: 'cat-hoodies', name: 'Hoodies', slug: 'hoodies', icon: 'bi-snow' },
    { id: 'cat-tshirts', name: 'T-Shirts', slug: 't-shirts', icon: 'bi-tshirt' },
    { id: 'cat-sneakers', name: 'Sneakers', slug: 'sneakers', icon: 'bi-bootstrap' },
    { id: 'cat-jackets', name: 'Jackets', slug: 'jackets', icon: 'bi-cloud' },
    { id: 'cat-pants', name: 'Cargo Pants', slug: 'cargo-pants', icon: 'bi-box' },
    { id: 'cat-street', name: 'Streetwear', slug: 'streetwear', icon: 'bi-lightning' },
  ],
  banners: [
    {
      id: 'bn-1',
      title: 'Winter Drop 2026',
      subtitle: 'Premium hoodies & jackets — up to 40% off',
      image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=1400&q=80',
      link: 'shop.html?category=hoodies',
      active: true,
      order: 1,
    },
    {
      id: 'bn-2',
      title: 'Street Essentials',
      subtitle: 'Cargo pants, tees & sneakers for Dhaka streets',
      image: 'https://images.unsplash.com/photo-1523381210434-271fa8a0c2e4?w=1400&q=80',
      link: 'shop.html?category=streetwear',
      active: true,
      order: 2,
    },
    {
      id: 'bn-3',
      title: 'New Arrivals',
      subtitle: 'Fresh fits every week — limited stock',
      image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1400&q=80',
      link: 'shop.html?sort=newest',
      active: true,
      order: 3,
    },
  ],
  coupons: [
    { id: 'cp-raven10', code: 'RAVEN10', discount: 10, type: 'percent', minOrder: 1500, active: true },
    { id: 'cp-flat200', code: 'FLAT200', discount: 200, type: 'flat', minOrder: 2000, active: true },
  ],
  products: [
    {
      id: 'p-001',
      name: 'RAVEN Obsidian Oversized Hoodie',
      slug: 'obsidian-oversized-hoodie',
      category: 'hoodies',
      price: 2890,
      discount: 15,
      stock: 42,
      status: 'active',
      badge: 'Bestseller',
      rating: 4.8,
      reviewCount: 124,
      featured: true,
      flashSale: true,
      trending: true,
      isNew: false,
      colors: ['#111111', '#2d2d2d', '#f5f5f5'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      images: [
        'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80',
        'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800&q=80',
      ],
      description: 'Heavyweight fleece hoodie with dropped shoulders. Premium cotton blend for Bangladesh weather.',
    },
    {
      id: 'p-002',
      name: 'Monochrome Essential Tee',
      slug: 'monochrome-essential-tee',
      category: 't-shirts',
      price: 890,
      discount: 0,
      stock: 120,
      status: 'active',
      badge: 'New',
      rating: 4.5,
      reviewCount: 67,
      featured: true,
      flashSale: false,
      trending: true,
      isNew: true,
      colors: ['#000000', '#ffffff', '#808080'],
      sizes: ['S', 'M', 'L', 'XL'],
      images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80'],
      description: '240 GSM combed cotton tee. Minimal RAVEN branding on chest.',
    },
    {
      id: 'p-003',
      name: 'Shadow Runner Sneakers',
      slug: 'shadow-runner-sneakers',
      category: 'sneakers',
      price: 4590,
      discount: 20,
      stock: 18,
      status: 'active',
      badge: 'Flash Sale',
      rating: 4.7,
      reviewCount: 89,
      featured: true,
      flashSale: true,
      trending: true,
      isNew: false,
      colors: ['#1a1a1a', '#ffffff'],
      sizes: ['40', '41', '42', '43', '44'],
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80'],
      description: 'Lightweight street runner with cushioned sole. All-day comfort.',
    },
    {
      id: 'p-004',
      name: 'Urban Shield Puffer Jacket',
      slug: 'urban-shield-puffer',
      category: 'jackets',
      price: 5490,
      discount: 25,
      stock: 0,
      status: 'active',
      badge: 'Sold Out',
      rating: 4.9,
      reviewCount: 45,
      featured: true,
      flashSale: false,
      trending: false,
      isNew: false,
      colors: ['#000000', '#1e3a5f'],
      sizes: ['M', 'L', 'XL'],
      images: ['https://images.unsplash.com/photo-1551028716-22cbce4d7c9f?w=800&q=80'],
      description: 'Water-resistant puffer with quilted panels. Winter essential.',
    },
    {
      id: 'p-005',
      name: 'Tactical Cargo Pants',
      slug: 'tactical-cargo-pants',
      category: 'cargo-pants',
      price: 2190,
      discount: 10,
      stock: 55,
      status: 'active',
      badge: null,
      rating: 4.6,
      reviewCount: 38,
      featured: false,
      flashSale: true,
      trending: true,
      isNew: true,
      colors: ['#2f2f2f', '#556b2f', '#000000'],
      sizes: ['28', '30', '32', '34', '36'],
      images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&q=80'],
      description: 'Relaxed fit cargo with multiple pockets. Durable ripstop fabric.',
    },
    {
      id: 'p-006',
      name: 'Nightfall Streetwear Set',
      slug: 'nightfall-streetwear-set',
      category: 'streetwear',
      price: 3990,
      discount: 12,
      stock: 24,
      status: 'active',
      badge: 'Bundle',
      rating: 4.4,
      reviewCount: 22,
      featured: true,
      flashSale: false,
      trending: true,
      isNew: true,
      colors: ['#111111'],
      sizes: ['M', 'L', 'XL'],
      images: ['https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&q=80'],
      description: 'Coordinated hoodie + cargo bundle. Save when you buy the set.',
    },
    {
      id: 'p-007',
      name: 'Graphite Zip Hoodie',
      slug: 'graphite-zip-hoodie',
      category: 'hoodies',
      price: 3190,
      discount: 0,
      stock: 36,
      status: 'active',
      badge: null,
      rating: 4.3,
      reviewCount: 51,
      featured: false,
      flashSale: false,
      trending: false,
      isNew: true,
      colors: ['#333333', '#000000'],
      sizes: ['S', 'M', 'L', 'XL'],
      images: ['https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800&q=80'],
      description: 'Full-zip hoodie with metal hardware. Clean street aesthetic.',
    },
    {
      id: 'p-008',
      name: 'Vintage Wash Oversized Tee',
      slug: 'vintage-wash-tee',
      category: 't-shirts',
      price: 1190,
      discount: 5,
      stock: 88,
      status: 'active',
      badge: null,
      rating: 4.2,
      reviewCount: 29,
      featured: false,
      flashSale: true,
      trending: false,
      isNew: false,
      colors: ['#4a4a4a', '#8b7355'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      images: ['https://images.unsplash.com/photo-1583743814966-6a7c754aeeda?w=800&q=80'],
      description: 'Acid wash oversized fit. Soft hand-feel after first wash.',
    },
    {
      id: 'p-009',
      name: 'Stealth Low-Top Sneakers',
      slug: 'stealth-low-top',
      category: 'sneakers',
      price: 3290,
      discount: 0,
      stock: 31,
      status: 'active',
      badge: null,
      rating: 4.5,
      reviewCount: 41,
      featured: false,
      flashSale: false,
      trending: true,
      isNew: false,
      colors: ['#000000', '#ffffff', '#c0c0c0'],
      sizes: ['39', '40', '41', '42', '43'],
      images: ['https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800&q=80'],
      description: 'Minimal leather-look low tops. Pairs with everything.',
    },
    {
      id: 'p-010',
      name: 'Bomber Core Jacket',
      slug: 'bomber-core-jacket',
      category: 'jackets',
      price: 4290,
      discount: 18,
      stock: 15,
      status: 'active',
      badge: 'Limited',
      rating: 4.7,
      reviewCount: 33,
      featured: true,
      flashSale: true,
      trending: false,
      isNew: false,
      colors: ['#000000', '#1a472a'],
      sizes: ['M', 'L', 'XL'],
      images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80'],
      description: 'Classic bomber silhouette with ribbed cuffs. Satin lining.',
    },
    {
      id: 'p-011',
      name: 'Wide-Leg Cargo Street',
      slug: 'wide-leg-cargo',
      category: 'cargo-pants',
      price: 2490,
      discount: 0,
      stock: 40,
      status: 'active',
      badge: null,
      rating: 4.4,
      reviewCount: 19,
      featured: false,
      flashSale: false,
      trending: false,
      isNew: true,
      colors: ['#000000', '#3d3d3d'],
      sizes: ['28', '30', '32', '34'],
      images: ['https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&q=80'],
      description: 'Wide-leg cargo with adjustable waist. Trend-forward cut.',
    },
    {
      id: 'p-012',
      name: 'RAVEN Logo Cap & Chain Pack',
      slug: 'logo-cap-chain-pack',
      category: 'streetwear',
      price: 1490,
      discount: 8,
      stock: 60,
      status: 'active',
      badge: 'Accessory',
      rating: 4.1,
      reviewCount: 14,
      featured: false,
      flashSale: true,
      trending: false,
      isNew: true,
      colors: ['#000000'],
      sizes: ['One Size'],
      images: ['https://images.unsplash.com/photo-1588850561407-ed78a282b3d9?w=800&q=80'],
      description: 'Embroidered cap with stainless chain. Complete the fit.',
    },
  ],
  reviews: [
    { id: 'rv-1', productId: 'p-001', userId: 'u-demo', userName: 'Arif H.', rating: 5, text: 'Perfect fit and quality. Worth every taka!', date: '2026-04-12' },
    { id: 'rv-2', productId: 'p-001', userId: 'u-demo2', userName: 'Sadia K.', rating: 4, text: 'Love the material. Shipping was fast to Dhaka.', date: '2026-04-08' },
    { id: 'rv-3', productId: 'p-003', userId: 'u-demo', userName: 'Arif H.', rating: 5, text: 'Super comfortable sneakers.', date: '2026-03-20' },
  ],
};
